name: mosaicenv
channels:
  - talley
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - anaconda-client
  - appdirs
  - cudadeconv # [osx]
  # - llspy-slm
  # - llspylibs
  - matplotlib
  - numpy
  - scipy
  - numba
  # - pyqt
  - pyside2>=5.12.3
  - qtpy>=1.7.0
  - sentry-sdk
  - tifffolder
  
  - sphinx
  - sphinx-autobuild
  - sphinxcontrib-napoleon
  - ipython>=7.7.0
  - black
  - flake8

  - pip
  - pip:
    - sphinx-rtd-theme
    - tifffile