name: mosaicenv
channels:
  - talley
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - anaconda-client
  - appdirs
  - llspy-slm
  - llspylibs
  - matplotlib
  - numpy
  - numba
  - pyqt
  - sentry-sdk
  - tifffolder
  
  - sphinx
  - sphinx-autobuild
  - sphinxcontrib-napoleon
  - ipython
  - black
  - flake8

  - pip
  - pip:
    - sphinx-rtd-theme
    - tifffile