name: llspydev
channels:
  - talley
  - talley/label/dev
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy >=1.0.0
  - matplotlib >=2.2
  - tifffile >=0.14.0
  - numba >=0.38.0
  - ipython
  - voluptuous
  - watchdog
  - click
  - pip
  - pyqt >=5.9.2
  - pyopencl
  - spimagine >=0.2.5
  - raven
  - llspy-slm
  - llspylibs >=0.1.3
  - llscd
  - tifffolder
  - parse
  - pigz
#  - lbzip2   # mac linux only
#  - tar ==1.29  # mac/linux only
  - pytest
  - pytest-qt
  - anaconda-client